### ISSUE TITLE
[C4GT] Sunbird-RC Integration with CORD

### ISSUE THREAD

**Issue by vatsa287** [dhiway/issuer-agent#39]
Please refer this [link](https://github.com/Sunbird-RC/sunbird-rc-core/pull/249#issue-1883812701). Which has implementation details.
For further development please connect 
Vikas: <vikas.tc@dhiway.com>
Discord Id: vikas_tc

### Pre Requisites

- Languages: Java
- Framework: SpringBoot

### Goal

- Old PR and new PR(updated code with Sunbird standards) is already present needs to setup Sunbird, CORD locally and test it out.

**Comment by Vikastc** [comment]
The pr is done, the pending task is to test it out if it is working as expected and make the required changes.
Are you well versed in java?

**Comment by zeel991** [comment]
> The pr is done, the pending task is to test it out if it is working as expected and make the required changes. Are you well versed in java?

I know Java , I haven't practiced it lately , I'll brush up my skills and start working on the task

**Comment by zeel991** [comment]
> The pr is done, the pending task is to test it out if it is working as expected and make the required changes. Are you well versed in java?

I know Java , will brush up and start contributing , it would be very helpful if you could send resources related to Springboot framework

**Comment by Vikastc** [comment]
Im not experienced in java, go through the pr let me know if you have any questions related to issuer_agent or cord

**Comment by Vikastc** [comment]
You can connect with me on discord if you have any doubts

**Comment by Vikastc** [comment]
@zeel991 Are you working on this?

**Comment by zeel991** [comment]
> @zeel991 Are you working on this?

Actually I have my academic tests rn , will soon start working on this
